swagger: "2.0"
info:
  title: "A Swagger API"
  description: "powered by Flasgger"
  termsOfService: "/tos"
  version: "0.0.1"

paths:
  /api/applications/:
    $ref: "./paths/applications/get.yml"
    post:
      $ref: "./paths/applications/post.yml"

  /api/jobs/:
    $ref: "./paths/jobs/get.yml"
    post:
      $ref: "./paths/jobs/post.yml"

  /api/jobs/{job_id}/bookmark:
    put:
      $ref: "./paths/jobs/put_bookmark.yml"

  /api/users/login:
    post:
      $ref: "./paths/users/login.yml"

  /api/users/register:
    post:
      $ref: "./paths/users/register.yml"

  /ping:
    get:
      summary: "A simple test endpoint"
      description: "Returns a pong response to check if the API is working."
      tags:
        - Test
      responses:
        200:
          description: "Pong response"
          examples:
            application/json:
              message: "pong"
